using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DealerLead
{
    public class DealerLeadUser
    {
        [Key]
       // [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        [Column("UserId")]
        public int UserId { get; set; }

        [Column("AzureADId")]
        public Guid AzureADId { get; set; }

        [Column("CreateDate")]

        [ScaffoldColumn(false)]//hides values
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]///auto-generated by database and set by database
        public DateTime? CreateDate { get; set; }


    }
}
