using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Threading.Tasks;

namespace DealerLead
{
   public class SupportedModel
    {
        [Key]
        [Column("ModelId")]
        public int ModelId { get; set; }

        [Display(Name = "Name")]
        [Column("ModelName")]
        public string ModelName { get; set; }

        [Column("MakeId")]
        public int MakeId { get; set; }

        public SupportedMake Make { get; set; }

        [ScaffoldColumn(false)]//hides values
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]//auto-generated by database and set by database
        public DateTime? CreateDate { get; set; }

        //hides values
        [ScaffoldColumn(false)]
        public DateTime? ModifyDate { get; set; }
    }

	//ModelId INT PRIMARY KEY IDENTITY,
	//ModelName NVARCHAR(30),
	//MakeId INT NOT NULL,
	//CreateDate DATETIME NOT NULL DEFAULT(getdate()),
	//ModifyDate DATETIME,
	//CONSTRAINT FK_SupportedModel_SupportedMake FOREIGN KEY(MakeId) REFERENCES SupportedMake
}
